"""add phone city country service_category to providers

Revision ID: 447eaa85e4ed
Revises: 86c1901c907d
Create Date: 2026-05-21 00:03:24.790464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447eaa85e4ed'
down_revision: Union[str, Sequence[str], None] = '86c1901c907d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('providers', sa.Column('service_category', sa.String(), nullable=True))
    op.add_column('providers', sa.Column('city', sa.String(), nullable=True))
    op.add_column('providers', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'country')
    op.drop_column('providers', 'city')
    op.drop_column('providers', 'service_category')
    op.drop_column('providers', 'phone')
    # ### end Alembic commands ###
