"""add user_id to providers

Revision ID: 86c1901c907d
Revises: a104cf1f5cc0
Create Date: 2026-05-20 23:29:00.679632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c1901c907d'
down_revision: Union[str, Sequence[str], None] = 'a104cf1f5cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_providers_user_id'), 'providers', ['user_id'], unique=True)
    op.create_foreign_key(None, 'providers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_index(op.f('ix_providers_user_id'), table_name='providers')
    op.drop_column('providers', 'user_id')
    # ### end Alembic commands ###
